import type * as vscode from "vscode";
import type { JobConfigUpdateWorkflow } from "../../commands/job/JobConfigUpdateWorkflow";
import type { JenkinsClientProvider } from "../../jenkins/JenkinsClientProvider";
import type { JenkinsDataService } from "../../jenkins/JenkinsDataService";
import type { JenkinsQueuePoller } from "../../queue/JenkinsQueuePoller";
import type { ArtifactRetrievalService } from "../../services/ArtifactRetrievalService";
import type { ArtifactStorageService } from "../../services/ArtifactStorageService";
import type { BuildConsoleExporter } from "../../services/BuildConsoleExporter";
import type { BuildLogService } from "../../services/BuildLogService";
import type { JobConfigDraftFilesystem } from "../../services/JobConfigDraftFilesystem";
import type { JobConfigDraftManager } from "../../services/JobConfigDraftManager";
import type { PendingInputRefreshCoordinator } from "../../services/PendingInputRefreshCoordinator";
import type { QueuedBuildWaiter } from "../../services/QueuedBuildWaiter";
import type { JenkinsEnvironmentStore } from "../../storage/JenkinsEnvironmentStore";
import type { JenkinsParameterPresetStore } from "../../storage/JenkinsParameterPresetStore";
import type { JenkinsPinStore } from "../../storage/JenkinsPinStore";
import type { JenkinsViewStateStore } from "../../storage/JenkinsViewStateStore";
import type { JenkinsWatchStore } from "../../storage/JenkinsWatchStore";
import type { JenkinsWorkbenchTreeDataProvider } from "../../tree/TreeDataProvider";
import type { TreeExpansionState } from "../../tree/TreeExpansionState";
import type { JenkinsTreeFilter } from "../../tree/TreeFilter";
import type { WorkbenchTreeElement } from "../../tree/TreeItems";
import type { DefaultJenkinsTreeNavigator } from "../../tree/TreeNavigator";
import type { ArtifactActionHandler } from "../../ui/ArtifactActionHandler";
import type { ArtifactPreviewProvider } from "../../ui/ArtifactPreviewProvider";
import type { BuildLogPreviewer } from "../../ui/BuildLogPreviewer";
import type { JobConfigPreviewer } from "../../ui/JobConfigPreviewer";
import type { JenkinsfileEnvironmentResolver } from "../../validation/JenkinsfileEnvironmentResolver";
import type { JenkinsfileMatcher } from "../../validation/JenkinsfileMatcher";
import type { JenkinsfileValidationCoordinator } from "../../validation/JenkinsfileValidationCoordinator";
import type { JenkinsfileValidationStatusBar } from "../../validation/JenkinsfileValidationStatusBar";
import type { JenkinsfileHoverProvider } from "../../validation/editor/JenkinsfileHoverProvider";
import type { JenkinsfileQuickFixProvider } from "../../validation/editor/JenkinsfileQuickFixProvider";
import type { JenkinsfileValidationCodeLensProvider } from "../../validation/editor/JenkinsfileValidationCodeLensProvider";
import type { JenkinsStatusPoller } from "../../watch/JenkinsStatusPoller";
import type { ExtensionRefreshHost } from "../ExtensionRefreshHost";
import type { JenkinsWorkbenchDeepLinkBuildHandler } from "../JenkinsWorkbenchDeepLinkBuildHandler";
import type { JenkinsWorkbenchDeepLinkJobHandler } from "../JenkinsWorkbenchDeepLinkJobHandler";
import type { JenkinsWorkbenchUriHandler } from "../JenkinsWorkbenchUriHandler";
import type { VscodeStatusNotifier } from "../VscodeStatusNotifier";

export interface ExtensionTokenMap {
  environmentStore: JenkinsEnvironmentStore;
  clientProvider: JenkinsClientProvider;
  dataService: JenkinsDataService;
  pendingInputCoordinator: PendingInputRefreshCoordinator;
  queuedBuildWaiter: QueuedBuildWaiter;
  consoleExporter: BuildConsoleExporter;
  buildLogService: BuildLogService;
  artifactRetrievalService: ArtifactRetrievalService;
  artifactStorageService: ArtifactStorageService;
  artifactPreviewProvider: ArtifactPreviewProvider;
  buildLogPreviewer: BuildLogPreviewer;
  jobConfigPreviewer: JobConfigPreviewer;
  jobConfigDraftFilesystem: JobConfigDraftFilesystem;
  jobConfigDraftManager: JobConfigDraftManager;
  jobConfigUpdateWorkflow: JobConfigUpdateWorkflow;
  artifactActionHandler: ArtifactActionHandler;
  watchStore: JenkinsWatchStore;
  presetStore: JenkinsParameterPresetStore;
  pinStore: JenkinsPinStore;
  viewStateStore: JenkinsViewStateStore;
  treeFilter: JenkinsTreeFilter;
  treeDataProvider: JenkinsWorkbenchTreeDataProvider;
  treeView: vscode.TreeView<WorkbenchTreeElement>;
  treeExpansionState: TreeExpansionState;
  treeNavigator: DefaultJenkinsTreeNavigator;
  jenkinsfileMatcher: JenkinsfileMatcher;
  jenkinsfileEnvironmentResolver: JenkinsfileEnvironmentResolver;
  jenkinsfileValidationCoordinator: JenkinsfileValidationCoordinator;
  jenkinsfileValidationStatusBar: JenkinsfileValidationStatusBar;
  statusNotifier: VscodeStatusNotifier;
  poller: JenkinsStatusPoller;
  queuePoller: JenkinsQueuePoller;
  refreshHost: ExtensionRefreshHost;
  buildDeepLinkHandler: JenkinsWorkbenchDeepLinkBuildHandler;
  jobDeepLinkHandler: JenkinsWorkbenchDeepLinkJobHandler;
  uriHandler: JenkinsWorkbenchUriHandler;
  jenkinsfileQuickFixProvider: JenkinsfileQuickFixProvider;
  jenkinsfileHoverProvider: JenkinsfileHoverProvider;
  jenkinsfileCodeLensProvider: JenkinsfileValidationCodeLensProvider;
}

export type ExtensionToken = keyof ExtensionTokenMap;
