import type * as vscode from "vscode";
import type { ReplayBuildWorkflow } from "../../commands/build/ReplayBuildWorkflow";
import type { JobConfigUpdateWorkflow } from "../../commands/job/JobConfigUpdateWorkflow";
import type { CurrentBranchActionExecutor } from "../../currentBranch/CurrentBranchActionExecutor";
import type { CurrentBranchCommandMapper } from "../../currentBranch/CurrentBranchCommandMapper";
import type { CurrentBranchGitHubPullRequestAdapter } from "../../currentBranch/CurrentBranchGitHubPullRequestAdapter";
import type { CurrentBranchJenkinsService } from "../../currentBranch/CurrentBranchJenkinsService";
import type { CurrentBranchLinkResolver } from "../../currentBranch/CurrentBranchLinkResolver";
import type { CurrentBranchLinkWorkflowService } from "../../currentBranch/CurrentBranchLinkWorkflowService";
import type { CurrentBranchPullRequestJobNameMatcher } from "../../currentBranch/CurrentBranchPullRequestJobMatcher";
import type { CurrentBranchPullRequestService } from "../../currentBranch/CurrentBranchPullRequestService";
import type { CurrentBranchRefreshCoordinator } from "../../currentBranch/CurrentBranchRefreshCoordinator";
import type { CurrentBranchRepositoryResolver } from "../../currentBranch/CurrentBranchRepositoryResolver";
import type { CurrentBranchStatusBar } from "../../currentBranch/CurrentBranchStatusBar";
import type { CurrentBranchStatusResolver } from "../../currentBranch/CurrentBranchStatusResolver";
import type { CurrentBranchTargetResolver } from "../../currentBranch/CurrentBranchTargetResolver";
import type { CurrentBranchWorkflowService } from "../../currentBranch/CurrentBranchWorkflowService";
import type { JenkinsClientProvider } from "../../jenkins/JenkinsClientProvider";
import type { JenkinsDataService } from "../../jenkins/JenkinsDataService";
import type { JenkinsfileIntelligenceConfigState } from "../../jenkinsfile/JenkinsfileIntelligenceConfigState";
import type { JenkinsfileStepCatalogService } from "../../jenkinsfile/JenkinsfileStepCatalogService";
import type { JenkinsfileCompletionProvider } from "../../jenkinsfile/editor/JenkinsfileCompletionProvider";
import type { JenkinsfileSignatureHelpProvider } from "../../jenkinsfile/editor/JenkinsfileSignatureHelpProvider";
import type { JenkinsQueuePoller } from "../../queue/JenkinsQueuePoller";
import type { ArtifactRetrievalService } from "../../services/ArtifactRetrievalService";
import type { ArtifactStorageService } from "../../services/ArtifactStorageService";
import type { BuildConsoleExporter } from "../../services/BuildConsoleExporter";
import type { BuildLogService } from "../../services/BuildLogService";
import type { JenkinsStatusRefreshService } from "../../services/JenkinsStatusRefreshService";
import type { JobConfigDraftFilesystem } from "../../services/JobConfigDraftFilesystem";
import type { JobConfigDraftManager } from "../../services/JobConfigDraftManager";
import type { PendingInputRefreshCoordinator } from "../../services/PendingInputRefreshCoordinator";
import type { QueuedBuildWaiter } from "../../services/QueuedBuildWaiter";
import type { ReplayDraftFilesystem } from "../../services/ReplayDraftFilesystem";
import type { ReplayDraftManager } from "../../services/ReplayDraftManager";
import type { JenkinsEnvironmentStore } from "../../storage/JenkinsEnvironmentStore";
import type { JenkinsParameterPresetStore } from "../../storage/JenkinsParameterPresetStore";
import type { JenkinsPinStore } from "../../storage/JenkinsPinStore";
import type { JenkinsRepositoryLinkStore } from "../../storage/JenkinsRepositoryLinkStore";
import type { JenkinsViewStateStore } from "../../storage/JenkinsViewStateStore";
import type { JenkinsWatchStore } from "../../storage/JenkinsWatchStore";
import type { JenkinsWorkbenchTreeDataProvider } from "../../tree/TreeDataProvider";
import type { TreeExpansionState } from "../../tree/TreeExpansionState";
import type { JenkinsTreeFilter } from "../../tree/TreeFilter";
import type { WorkbenchTreeElement } from "../../tree/TreeItems";
import type { DefaultJenkinsTreeNavigator } from "../../tree/TreeNavigator";
import type { ArtifactActionHandler } from "../../ui/ArtifactActionHandler";
import type { ArtifactPreviewProvider } from "../../ui/ArtifactPreviewProvider";
import type { BuildLogPreviewer } from "../../ui/BuildLogPreviewer";
import type { JobConfigPreviewer } from "../../ui/JobConfigPreviewer";
import type { JenkinsfileEnvironmentResolver } from "../../validation/JenkinsfileEnvironmentResolver";
import type { JenkinsfileMatcher } from "../../validation/JenkinsfileMatcher";
import type { JenkinsfileValidationCoordinator } from "../../validation/JenkinsfileValidationCoordinator";
import type { JenkinsfileValidationStatusBar } from "../../validation/JenkinsfileValidationStatusBar";
import type { JenkinsfileHoverProvider } from "../../validation/editor/JenkinsfileHoverProvider";
import type { JenkinsfileQuickFixProvider } from "../../validation/editor/JenkinsfileQuickFixProvider";
import type { JenkinsfileValidationCodeLensProvider } from "../../validation/editor/JenkinsfileValidationCodeLensProvider";
import type { JenkinsStatusPoller } from "../../watch/JenkinsStatusPoller";
import type { ExtensionRefreshHost } from "../ExtensionRefreshHost";
import type { JenkinsWorkbenchDeepLinkBuildHandler } from "../JenkinsWorkbenchDeepLinkBuildHandler";
import type { JenkinsWorkbenchDeepLinkJobHandler } from "../JenkinsWorkbenchDeepLinkJobHandler";
import type { JenkinsWorkbenchUriHandler } from "../JenkinsWorkbenchUriHandler";
import type { VscodeStatusNotifier } from "../VscodeStatusNotifier";

export interface ExtensionTokenMap {
  environmentStore: JenkinsEnvironmentStore;
  clientProvider: JenkinsClientProvider;
  dataService: JenkinsDataService;
  pendingInputCoordinator: PendingInputRefreshCoordinator;
  queuedBuildWaiter: QueuedBuildWaiter;
  consoleExporter: BuildConsoleExporter;
  buildLogService: BuildLogService;
  artifactRetrievalService: ArtifactRetrievalService;
  artifactStorageService: ArtifactStorageService;
  artifactPreviewProvider: ArtifactPreviewProvider;
  buildLogPreviewer: BuildLogPreviewer;
  jobConfigPreviewer: JobConfigPreviewer;
  jobConfigDraftFilesystem: JobConfigDraftFilesystem;
  jobConfigDraftManager: JobConfigDraftManager;
  jobConfigUpdateWorkflow: JobConfigUpdateWorkflow;
  replayDraftFilesystem: ReplayDraftFilesystem;
  replayDraftManager: ReplayDraftManager;
  replayBuildWorkflow: ReplayBuildWorkflow;
  artifactActionHandler: ArtifactActionHandler;
  watchStore: JenkinsWatchStore;
  presetStore: JenkinsParameterPresetStore;
  pinStore: JenkinsPinStore;
  repositoryLinkStore: JenkinsRepositoryLinkStore;
  viewStateStore: JenkinsViewStateStore;
  currentBranchRepositoryResolver: CurrentBranchRepositoryResolver;
  currentBranchLinkResolver: CurrentBranchLinkResolver;
  currentBranchGitHubPullRequestAdapter: CurrentBranchGitHubPullRequestAdapter;
  currentBranchPullRequestService: CurrentBranchPullRequestService;
  currentBranchPullRequestJobMatcher: CurrentBranchPullRequestJobNameMatcher;
  currentBranchRefreshCoordinator: CurrentBranchRefreshCoordinator;
  currentBranchTargetResolver: CurrentBranchTargetResolver;
  currentBranchStatusResolver: CurrentBranchStatusResolver;
  currentBranchLinkWorkflowService: CurrentBranchLinkWorkflowService;
  currentBranchActionExecutor: CurrentBranchActionExecutor;
  currentBranchCommandMapper: CurrentBranchCommandMapper;
  currentBranchService: CurrentBranchJenkinsService;
  currentBranchWorkflowService: CurrentBranchWorkflowService;
  currentBranchStatusBar: CurrentBranchStatusBar;
  treeFilter: JenkinsTreeFilter;
  treeDataProvider: JenkinsWorkbenchTreeDataProvider;
  treeView: vscode.TreeView<WorkbenchTreeElement>;
  treeExpansionState: TreeExpansionState;
  treeNavigator: DefaultJenkinsTreeNavigator;
  jenkinsfileMatcher: JenkinsfileMatcher;
  jenkinsfileEnvironmentResolver: JenkinsfileEnvironmentResolver;
  jenkinsfileValidationCoordinator: JenkinsfileValidationCoordinator;
  jenkinsfileValidationStatusBar: JenkinsfileValidationStatusBar;
  jenkinsfileIntelligenceConfigState: JenkinsfileIntelligenceConfigState;
  jenkinsfileStepCatalogService: JenkinsfileStepCatalogService;
  statusRefreshService: JenkinsStatusRefreshService;
  statusNotifier: VscodeStatusNotifier;
  poller: JenkinsStatusPoller;
  queuePoller: JenkinsQueuePoller;
  refreshHost: ExtensionRefreshHost;
  buildDeepLinkHandler: JenkinsWorkbenchDeepLinkBuildHandler;
  jobDeepLinkHandler: JenkinsWorkbenchDeepLinkJobHandler;
  uriHandler: JenkinsWorkbenchUriHandler;
  jenkinsfileQuickFixProvider: JenkinsfileQuickFixProvider;
  jenkinsfileHoverProvider: JenkinsfileHoverProvider;
  jenkinsfileCodeLensProvider: JenkinsfileValidationCodeLensProvider;
  jenkinsfileCompletionProvider: JenkinsfileCompletionProvider;
  jenkinsfileSignatureHelpProvider: JenkinsfileSignatureHelpProvider;
}

export type ExtensionToken = keyof ExtensionTokenMap;
