// Approximations of the `--vscode-*` variables VS Code injects into webviews,
// taken from the Dark Modern, Light Modern and Dark High Contrast themes. Only
// the variables the panels actually read are listed.

const shared: Record<string, string> = {
  "--vscode-font-family": '-apple-system, BlinkMacSystemFont, "Segoe WPC", "Segoe UI", sans-serif',
  "--vscode-font-size": "13px",
  "--vscode-editor-font-family": 'Menlo, Monaco, "Courier New", monospace',
  "--vscode-editor-font-size": "12px"
};

const dark: Record<string, string> = {
  ...shared,
  "--vscode-editor-background": "#1f1f1f",
  "--vscode-editor-foreground": "#cccccc",
  "--vscode-foreground": "#cccccc",
  "--vscode-descriptionForeground": "#9d9d9d",
  "--vscode-focusBorder": "#0078d4",
  "--vscode-textLink-foreground": "#4daafc",
  "--vscode-textLink-activeForeground": "#4daafc",
  "--vscode-panel-border": "#2b2b2b",
  "--vscode-editorWidget-background": "#202020",
  "--vscode-list-hoverBackground": "#2a2d2e",
  "--vscode-list-activeSelectionBackground": "#04395e",
  "--vscode-list-activeSelectionForeground": "#ffffff",
  "--vscode-button-background": "#0078d4",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#026ec1",
  "--vscode-button-secondaryBackground": "#313131",
  "--vscode-button-secondaryForeground": "#cccccc",
  "--vscode-button-secondaryHoverBackground": "#3c3c3c",
  "--vscode-input-background": "#313131",
  "--vscode-input-foreground": "#cccccc",
  "--vscode-input-border": "#3c3c3c",
  "--vscode-input-placeholderForeground": "#989898",
  "--vscode-inputValidation-errorBackground": "#5a1d1d",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-warningBackground": "#352a05",
  "--vscode-inputValidation-warningBorder": "#b89500",
  "--vscode-inputValidation-infoBackground": "#063b49",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-testing-iconPassed": "#73c991",
  "--vscode-testing-iconFailed": "#f14c4c",
  "--vscode-editorWarning-foreground": "#cca700",
  "--vscode-terminal-background": "#181818",
  "--vscode-terminal-foreground": "#cccccc",
  "--vscode-sideBar-background": "#181818",
  "--vscode-scrollbarSlider-background": "#79797966",
  "--vscode-scrollbarSlider-hoverBackground": "#646464b3",
  "--vscode-scrollbarSlider-activeBackground": "#bfbfbf66",
  "--vscode-progressBar-background": "#0078d4",
  "--vscode-editor-selectionBackground": "#264f78",
  "--vscode-editor-findMatchHighlightBackground": "#ea5c0055",
  "--vscode-editor-findMatchBackground": "#9e6a03",
  "--vscode-checkbox-background": "#313131",
  "--vscode-checkbox-border": "#3c3c3c",
  "--vscode-checkbox-foreground": "#cccccc",
  "--vscode-badge-background": "#616161",
  "--vscode-badge-foreground": "#f8f8f8"
};

const light: Record<string, string> = {
  ...shared,
  "--vscode-editor-background": "#ffffff",
  "--vscode-editor-foreground": "#3b3b3b",
  "--vscode-foreground": "#3b3b3b",
  "--vscode-descriptionForeground": "#616161",
  "--vscode-focusBorder": "#005fb8",
  "--vscode-textLink-foreground": "#005fb8",
  "--vscode-textLink-activeForeground": "#005fb8",
  "--vscode-panel-border": "#e5e5e5",
  "--vscode-editorWidget-background": "#f8f8f8",
  "--vscode-list-hoverBackground": "#f2f2f2",
  "--vscode-list-activeSelectionBackground": "#e8e8e8",
  "--vscode-list-activeSelectionForeground": "#000000",
  "--vscode-button-background": "#005fb8",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#0258a8",
  "--vscode-button-secondaryBackground": "#e5e5e5",
  "--vscode-button-secondaryForeground": "#3b3b3b",
  "--vscode-button-secondaryHoverBackground": "#cccccc",
  "--vscode-input-background": "#ffffff",
  "--vscode-input-foreground": "#3b3b3b",
  "--vscode-input-border": "#cecece",
  "--vscode-input-placeholderForeground": "#767676",
  "--vscode-inputValidation-errorBackground": "#f2dede",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-warningBackground": "#f6f5d2",
  "--vscode-inputValidation-warningBorder": "#b89500",
  "--vscode-inputValidation-infoBackground": "#d6ecf2",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-testing-iconPassed": "#388a34",
  "--vscode-testing-iconFailed": "#f14c4c",
  "--vscode-editorWarning-foreground": "#bf8803",
  "--vscode-terminal-background": "#ffffff",
  "--vscode-terminal-foreground": "#3b3b3b",
  "--vscode-sideBar-background": "#f8f8f8",
  "--vscode-scrollbarSlider-background": "#64646466",
  "--vscode-scrollbarSlider-hoverBackground": "#646464b3",
  "--vscode-scrollbarSlider-activeBackground": "#00000099",
  "--vscode-progressBar-background": "#005fb8",
  "--vscode-editor-selectionBackground": "#add6ff",
  "--vscode-editor-findMatchHighlightBackground": "#ea5c0055",
  "--vscode-editor-findMatchBackground": "#a8ac94",
  "--vscode-checkbox-background": "#f8f8f8",
  "--vscode-checkbox-border": "#cecece",
  "--vscode-checkbox-foreground": "#3b3b3b",
  "--vscode-badge-background": "#cccccc",
  "--vscode-badge-foreground": "#3b3b3b"
};

const highContrast: Record<string, string> = {
  ...dark,
  "--vscode-editor-background": "#000000",
  "--vscode-editor-foreground": "#ffffff",
  "--vscode-foreground": "#ffffff",
  "--vscode-descriptionForeground": "#ffffffb3",
  "--vscode-contrastBorder": "#6fc3df",
  "--vscode-contrastActiveBorder": "#f38518",
  "--vscode-focusBorder": "#f38518",
  "--vscode-editorWidget-background": "#0c141f",
  "--vscode-sideBar-background": "#000000",
  "--vscode-list-hoverBackground": "transparent",
  "--vscode-button-background": "#000000",
  "--vscode-input-background": "#000000",
  "--vscode-terminal-background": "#000000",
  "--vscode-testing-iconPassed": "#73c991",
  "--vscode-testing-iconFailed": "#f48771"
};

export type PreviewThemeName = "dark" | "light" | "hc";

export const previewThemes: Record<
  PreviewThemeName,
  { bodyClass: string; vars: Record<string, string> }
> = {
  dark: { bodyClass: "vscode-dark", vars: dark },
  light: { bodyClass: "vscode-light", vars: light },
  hc: { bodyClass: "vscode-high-contrast", vars: highContrast }
};
